### ISSUE TITLE
Help needed : Can data from Redis be returned as part of SOLR doc.

### ISSUE THREAD

**Issue by InternetMaster1** [sematext/solr-redis#31]
Can this plugin be used to fetch the data stored in Redis as part of the solr result set, i.e. in docs. The description looks more like the Redis data can be used in the function queries for boosting, sorting, etc. Anyone has experience with this?

Please read this post to learn about my requirement. Thanks

http://stackoverflow.com/questions/34221511/dynamic-data-in-solr-like-counts-viewcounts-etc-nrt-vs-redis

**Comment by prog8** [comment]
You are right this plugin uses data from Redis to filter documents. Currently there is no way to fetch data per document and attach it to the response. I think this could be implemented but would require some effort. Why can't you search (in Solr) for matching documents and when you receive a response you know document IDs so you can fetch additional data from Redis by these IDs.

**Comment by InternetMaster1** [comment]
Ok, your second option the option of fetching data from Redis after getting
IDs from SOLR sounds good, we can do that.

For our other use case, where we store document scores in Redis, (which is
updated atomically live), then in the Hot tab, we need only those docs
which have score greater than say 500.

Is this possible using the solr-redis plugin? And what command or query to
use? Any pointers would be great!

**Comment by prog8** [comment]
Yes it is possible to use this plugin for selecting only documents with scores higher than 500. You'll have to use ZRANGE to store scores in Redis and command like:

```q=*:*&fq={!redis command=ZRANGE key=some_redis_key range_start=500 range_end=1000}field_which_you_use_to_filter```

You only have to keep in mind one thing. Solr-redis plugin is not a good solution if you will return lots of results from ZRANGE. It will work OK if the ZRANGE has lets say 1000 or 10000 results but it work very very bad if you return 10M results (mostly because of the networking and heavy Lucene query which will be produced). This means that if you have eg 20M documents in Solr and you want to store scores for each of them in Redis and 10M of them has score from range 500 to 1000 so ZRANGE  returns 10M document IDs than it is a bad solution.

From the other side you can consider using groups of documents with the same score. Lets consider this example

```
doc1 : {id: 1, group:1}
doc2 : {id: 2, group:1}
doc3 : {id: 2, group:1}
doc4 : {id: 2, group:2}
doc5 : {id: 2, group:2}
doc6 : {id: 2, group:2}
```
You have 6 documents and you know that those in group 1 will always have the same score than other docs within this group and you know that documents in group 2 will also have the same scores than other documents in group 2. Then you can use such a command:

```q=*:*&fq={!redis command=ZRANGE key=some_redis_key range_start=500 range_end=1000}group```


There is one more potential approach. If you know that queries you run finds only small number of documents (eg. 100 or 1000) you could consider extending solr-redis plugin (patch welcome :) ) with a post filter. This means when Solr query is executed internally and eg. 1000 documents are found Solr can fetch score for those 1000 documents and use post filter on them.

If you have further questions don't hesitate to ask

**Comment by InternetMaster1** [comment]
Those are some nice suggestions!

Another option for us could be to use External File Fields option in SOLR,
wherein the scores for all the docs are stored in an external file and
loaded into SOLR (at intervals we decide to commit). These scores can then
be directly used in function queries.

You have any experience with EFF? That would be scalable to millions of
records, right?

I guess that is beyond the scope of this github forums :)

**Comment by prog8** [comment]
I used External File Field in the past but it is also better to use it when you have groups of documents instead of attaching score to each document by ID. From what I remember for millions of key=value pairs in EFF the time of EFF reload was quite high and you are right that EFF is probably beyond this github forum :)

**Comment by InternetMaster1** [comment]
Thanks a lot for all your help! You are a rockstar :)

**Comment by prog8** [comment]
:blush:

**Comment by prog8** [comment]
This issue can be closed.
